Base
jesscxu/sfmovies pull request #1
Opened 2017-04-05 18:30 UTC by jesscxu

initialized the node package, set up configurations, and set up the server so that the application can now run

2017-04-05 19:29 UTC, mgartner requested changes

2017-04-05 19:29 UTC, mgartner commented on config/development.js
> +
nit: remove extra 3 extra lines at the end of the file

2017-04-05 19:29 UTC, mgartner commented on lib/index.js
> +});
nit: add a new line here. let's talk about this one IRL

2017-04-05 19:29 UTC, mgartner commented on lib/server.js
> +module.exports = server;
nit: add a new line here

2017-04-06 16:44 UTC, mgartner approved these changes
LGTM

2017-04-06 18:40 UTC, itsachen approved these changes
LGTM!

2017-04-06 18:40 UTC, itsachen commented on lib/index.js
> +const Util = require('util');
Nit: Generally we separate external and internal file imports with a newline, as well as alphabetize them and align their `=`'s. See [this section](https://github.com/lob/lob-api/blob/master/src/plugins/features/addresses/index.js#L3-L10) from `lob-api` as an example.

2017-04-07 18:16 UTC, merged